# for documentation, see:
#   https://docs.docker.com/compose/yml/
#   https://blog.docker.com/2015/02/scaling-docker-with-swarm/
#   https://github.com/docker/compose/blob/129092b7/docs/yml.md#variable-substitution

master:
  image: snufkin/spark-base
  net: host
  command:
  - bin/spark-class
  - org.apache.spark.deploy.master.Master

worker:
  image: snufkin/spark-base
  net: host
  command:
  - bin/spark-class
  - org.apache.spark.deploy.worker.Worker
  - spark://${SPARK_MASTER_HOST}:7077

shell:
  image: snufkin/spark-base
  net: host
  command:
  - bin/spark-shell
  - --master spark://${${SPARK_MASTER_HOST}}:7077


# /spark/bin/spark-class org.apache.spark.deploy.master.Master