# for documentation, see:
#   https://docs.docker.com/compose/yml/
#   https://blog.docker.com/2015/02/scaling-docker-with-swarm/
#   https://github.com/docker/compose/blob/129092b7/docs/yml.md#variable-substitution

# https://github.com/docker/swarm/tree/master/scheduler/filter#affinity-filter

base:
  image: rvion/spark:0.1
  net: host
  environment:
    MASTER_PATH: 192.168.99.100:7077
    # MASTER_PATH: ${SPARK_MASTER_HOST}

master:
  extends:
    service: base
  command: ./start-master.sh
  environment:
    affinity:master==true

worker:
  extends:
    service: base
  command: ./start-worker.sh

shell:
  extends:
    service: base
  command: ./start-shell.sh

# docker run --net=host -it --rm rvion/spark SPARK_LOCAL_IP=$(/spark/getIpOnInterface.sh eth1) bin/spark-class org.apache.spark.deploy.master.Master